/* eslint-disable */
// @generated by protobuf-ts 2.11.1 with parameter generate_dependencies,ts_nocheck,eslint_disable
// @generated from protobuf file "replicant/service.proto" (package "elephant.replicant", syntax proto3)
// tslint:disable
// @ts-nocheck
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message elephant.replicant.SendDocumentRequest
 */
export interface SendDocumentRequest {
    /**
     * The UUID of the document to replicate.
     *
     * @generated from protobuf field: string uuid = 1
     */
    uuid: string;
    /**
     * Force replication even if the document has already been replicated.
     *
     * @generated from protobuf field: bool force = 2
     */
    force: boolean;
}
/**
 * @generated from protobuf message elephant.replicant.SendDocumentResponse
 */
export interface SendDocumentResponse {
    /**
     * The version of the document that was replicated to the target.
     *
     * @generated from protobuf field: int64 target_version = 1
     */
    targetVersion: bigint;
}
/**
 * ConfigureTargetRequest creates or updates a replication target.
 *
 * @generated from protobuf message elephant.replicant.ConfigureTargetRequest
 */
export interface ConfigureTargetRequest {
    /**
     * Name is the identifier for the replication target.
     *
     * @generated from protobuf field: string name = 1
     */
    name: string;
    /**
     * The URL of the target repository to replicate to.
     *
     * @generated from protobuf field: string repository_url = 2
     */
    repositoryUrl: string;
    /**
     * The OIDC discovery configuration URL for target authentication.
     *
     * @generated from protobuf field: string oidc_config = 3
     */
    oidcConfig: string;
    /**
     * The OAuth2 client ID for target authentication.
     *
     * @generated from protobuf field: string client_id = 4
     */
    clientId: string;
    /**
     * The OAuth2 client secret for target authentication.
     *
     * @generated from protobuf field: string client_secret = 5
     */
    clientSecret: string;
    /**
     * The event log position to start replication from.
     *
     * @generated from protobuf field: int64 start_from = 6
     */
    startFrom: bigint;
    /**
     * Sync configuration controlling what gets replicated.
     *
     * @generated from protobuf field: elephant.replicant.SyncConfig config = 7
     */
    config?: SyncConfig;
}
/**
 * SyncConfig controls what documents and content are replicated.
 *
 * @generated from protobuf message elephant.replicant.SyncConfig
 */
export interface SyncConfig {
    /**
     * Accept and skip documents that fail to replicate instead of blocking.
     *
     * @generated from protobuf field: bool accept_errors = 1
     */
    acceptErrors: boolean;
    /**
     * Replicate all attachments for documents.
     *
     * @generated from protobuf field: bool all_attachments = 2
     */
    allAttachments: boolean;
    /**
     * Document types to exclude from replication.
     *
     * @generated from protobuf field: repeated string ignore_types = 3
     */
    ignoreTypes: string[];
    /**
     * Sections to exclude from replication, identified by document type and
     * section UUID.
     *
     * @generated from protobuf field: repeated elephant.replicant.SectionForType ignore_sections = 4
     */
    ignoreSections: SectionForType[];
    /**
     * Specific attachments to include when all_attachments is false.
     *
     * @generated from protobuf field: repeated elephant.replicant.AttachmentForType include_attachments = 5
     */
    includeAttachments: AttachmentForType[];
    /**
     * Ignore events generated by these client subs.
     *
     * @generated from protobuf field: repeated string ignore_subs = 6
     */
    ignoreSubs: string[];
}
/**
 * SectionForType identifies a section to ignore for a specific document type.
 *
 * @generated from protobuf message elephant.replicant.SectionForType
 */
export interface SectionForType {
    /**
     * The document type, e.g. "core/event".
     *
     * @generated from protobuf field: string type = 1
     */
    type: string;
    /**
     * The UUID of the section to ignore.
     *
     * @generated from protobuf field: string section_uuid = 2
     */
    sectionUuid: string;
}
/**
 * AttachmentForType identifies an attachment to include for a specific document
 * type. Format in environment variable: "name.type", e.g. "image.core/image".
 *
 * @generated from protobuf message elephant.replicant.AttachmentForType
 */
export interface AttachmentForType {
    /**
     * The attachment name, e.g. "image".
     *
     * @generated from protobuf field: string type = 1
     */
    type: string;
    /**
     * The document type, e.g. "core/image".
     *
     * @generated from protobuf field: string name = 2
     */
    name: string;
}
/**
 * @generated from protobuf message elephant.replicant.ConfigureTargetResponse
 */
export interface ConfigureTargetResponse {
}
/**
 * @generated from protobuf message elephant.replicant.RemoveTargetRequest
 */
export interface RemoveTargetRequest {
    /**
     * Name of the replication target to remove.
     *
     * @generated from protobuf field: string name = 1
     */
    name: string;
}
/**
 * @generated from protobuf message elephant.replicant.RemoveTargetResponse
 */
export interface RemoveTargetResponse {
}
/**
 * @generated from protobuf message elephant.replicant.ChangeTargetStateRequest
 */
export interface ChangeTargetStateRequest {
    /**
     * Name of the replication target.
     *
     * @generated from protobuf field: string name = 1
     */
    name: string;
    /**
     * The action to perform on the target.
     *
     * @generated from protobuf field: elephant.replicant.TargetAction action = 2
     */
    action: TargetAction;
}
/**
 * @generated from protobuf message elephant.replicant.ChangeTargetStateResponse
 */
export interface ChangeTargetStateResponse {
}
/**
 * @generated from protobuf message elephant.replicant.GetTargetStateRequest
 */
export interface GetTargetStateRequest {
    /**
     * Name of the replication target.
     *
     * @generated from protobuf field: string name = 1
     */
    name: string;
}
/**
 * @generated from protobuf message elephant.replicant.GetTargetStateResponse
 */
export interface GetTargetStateResponse {
    /**
     * The current state of the replication target.
     *
     * @generated from protobuf field: elephant.replicant.TargetState state = 1
     */
    state: TargetState;
}
/**
 * TargetAction is the action to take on a replication target.
 *
 * @generated from protobuf enum elephant.replicant.TargetAction
 */
export enum TargetAction {
    /**
     * @generated from protobuf enum value: TARGET_ACTION_UNSPECIFIED = 0;
     */
    UNSPECIFIED = 0,
    /**
     * @generated from protobuf enum value: TARGET_ACTION_START = 1;
     */
    START = 1,
    /**
     * @generated from protobuf enum value: TARGET_ACTION_STOP = 2;
     */
    STOP = 2
}
/**
 * TargetState describes the current runtime state of a replication target.
 *
 * @generated from protobuf enum elephant.replicant.TargetState
 */
export enum TargetState {
    /**
     * @generated from protobuf enum value: TARGET_STATE_UNSPECIFIED = 0;
     */
    UNSPECIFIED = 0,
    /**
     * @generated from protobuf enum value: TARGET_STATE_RUNNING = 1;
     */
    RUNNING = 1,
    /**
     * @generated from protobuf enum value: TARGET_STATE_STARTING = 2;
     */
    STARTING = 2,
    /**
     * @generated from protobuf enum value: TARGET_STATE_STOPPING = 3;
     */
    STOPPING = 3,
    /**
     * @generated from protobuf enum value: TARGET_STATE_STOPPED = 4;
     */
    STOPPED = 4
}
// @generated message type with reflection information, may provide speed optimized methods
class SendDocumentRequest$Type extends MessageType<SendDocumentRequest> {
    constructor() {
        super("elephant.replicant.SendDocumentRequest", [
            { no: 1, name: "uuid", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "force", kind: "scalar", T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
    create(value?: PartialMessage<SendDocumentRequest>): SendDocumentRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.uuid = "";
        message.force = false;
        if (value !== undefined)
            reflectionMergePartial<SendDocumentRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: SendDocumentRequest): SendDocumentRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string uuid */ 1:
                    message.uuid = reader.string();
                    break;
                case /* bool force */ 2:
                    message.force = reader.bool();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: SendDocumentRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string uuid = 1; */
        if (message.uuid !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.uuid);
        /* bool force = 2; */
        if (message.force !== false)
            writer.tag(2, WireType.Varint).bool(message.force);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message elephant.replicant.SendDocumentRequest
 */
export const SendDocumentRequest = new SendDocumentRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class SendDocumentResponse$Type extends MessageType<SendDocumentResponse> {
    constructor() {
        super("elephant.replicant.SendDocumentResponse", [
            { no: 1, name: "target_version", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ }
        ]);
    }
    create(value?: PartialMessage<SendDocumentResponse>): SendDocumentResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.targetVersion = 0n;
        if (value !== undefined)
            reflectionMergePartial<SendDocumentResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: SendDocumentResponse): SendDocumentResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int64 target_version */ 1:
                    message.targetVersion = reader.int64().toBigInt();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: SendDocumentResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int64 target_version = 1; */
        if (message.targetVersion !== 0n)
            writer.tag(1, WireType.Varint).int64(message.targetVersion);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message elephant.replicant.SendDocumentResponse
 */
export const SendDocumentResponse = new SendDocumentResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ConfigureTargetRequest$Type extends MessageType<ConfigureTargetRequest> {
    constructor() {
        super("elephant.replicant.ConfigureTargetRequest", [
            { no: 1, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "repository_url", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "oidc_config", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "client_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "client_secret", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 6, name: "start_from", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 7, name: "config", kind: "message", T: () => SyncConfig }
        ]);
    }
    create(value?: PartialMessage<ConfigureTargetRequest>): ConfigureTargetRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.name = "";
        message.repositoryUrl = "";
        message.oidcConfig = "";
        message.clientId = "";
        message.clientSecret = "";
        message.startFrom = 0n;
        if (value !== undefined)
            reflectionMergePartial<ConfigureTargetRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ConfigureTargetRequest): ConfigureTargetRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string name */ 1:
                    message.name = reader.string();
                    break;
                case /* string repository_url */ 2:
                    message.repositoryUrl = reader.string();
                    break;
                case /* string oidc_config */ 3:
                    message.oidcConfig = reader.string();
                    break;
                case /* string client_id */ 4:
                    message.clientId = reader.string();
                    break;
                case /* string client_secret */ 5:
                    message.clientSecret = reader.string();
                    break;
                case /* int64 start_from */ 6:
                    message.startFrom = reader.int64().toBigInt();
                    break;
                case /* elephant.replicant.SyncConfig config */ 7:
                    message.config = SyncConfig.internalBinaryRead(reader, reader.uint32(), options, message.config);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ConfigureTargetRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string name = 1; */
        if (message.name !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.name);
        /* string repository_url = 2; */
        if (message.repositoryUrl !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.repositoryUrl);
        /* string oidc_config = 3; */
        if (message.oidcConfig !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.oidcConfig);
        /* string client_id = 4; */
        if (message.clientId !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.clientId);
        /* string client_secret = 5; */
        if (message.clientSecret !== "")
            writer.tag(5, WireType.LengthDelimited).string(message.clientSecret);
        /* int64 start_from = 6; */
        if (message.startFrom !== 0n)
            writer.tag(6, WireType.Varint).int64(message.startFrom);
        /* elephant.replicant.SyncConfig config = 7; */
        if (message.config)
            SyncConfig.internalBinaryWrite(message.config, writer.tag(7, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message elephant.replicant.ConfigureTargetRequest
 */
export const ConfigureTargetRequest = new ConfigureTargetRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class SyncConfig$Type extends MessageType<SyncConfig> {
    constructor() {
        super("elephant.replicant.SyncConfig", [
            { no: 1, name: "accept_errors", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 2, name: "all_attachments", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 3, name: "ignore_types", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "ignore_sections", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => SectionForType },
            { no: 5, name: "include_attachments", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => AttachmentForType },
            { no: 6, name: "ignore_subs", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<SyncConfig>): SyncConfig {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.acceptErrors = false;
        message.allAttachments = false;
        message.ignoreTypes = [];
        message.ignoreSections = [];
        message.includeAttachments = [];
        message.ignoreSubs = [];
        if (value !== undefined)
            reflectionMergePartial<SyncConfig>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: SyncConfig): SyncConfig {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* bool accept_errors */ 1:
                    message.acceptErrors = reader.bool();
                    break;
                case /* bool all_attachments */ 2:
                    message.allAttachments = reader.bool();
                    break;
                case /* repeated string ignore_types */ 3:
                    message.ignoreTypes.push(reader.string());
                    break;
                case /* repeated elephant.replicant.SectionForType ignore_sections */ 4:
                    message.ignoreSections.push(SectionForType.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                case /* repeated elephant.replicant.AttachmentForType include_attachments */ 5:
                    message.includeAttachments.push(AttachmentForType.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                case /* repeated string ignore_subs */ 6:
                    message.ignoreSubs.push(reader.string());
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: SyncConfig, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* bool accept_errors = 1; */
        if (message.acceptErrors !== false)
            writer.tag(1, WireType.Varint).bool(message.acceptErrors);
        /* bool all_attachments = 2; */
        if (message.allAttachments !== false)
            writer.tag(2, WireType.Varint).bool(message.allAttachments);
        /* repeated string ignore_types = 3; */
        for (let i = 0; i < message.ignoreTypes.length; i++)
            writer.tag(3, WireType.LengthDelimited).string(message.ignoreTypes[i]);
        /* repeated elephant.replicant.SectionForType ignore_sections = 4; */
        for (let i = 0; i < message.ignoreSections.length; i++)
            SectionForType.internalBinaryWrite(message.ignoreSections[i], writer.tag(4, WireType.LengthDelimited).fork(), options).join();
        /* repeated elephant.replicant.AttachmentForType include_attachments = 5; */
        for (let i = 0; i < message.includeAttachments.length; i++)
            AttachmentForType.internalBinaryWrite(message.includeAttachments[i], writer.tag(5, WireType.LengthDelimited).fork(), options).join();
        /* repeated string ignore_subs = 6; */
        for (let i = 0; i < message.ignoreSubs.length; i++)
            writer.tag(6, WireType.LengthDelimited).string(message.ignoreSubs[i]);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message elephant.replicant.SyncConfig
 */
export const SyncConfig = new SyncConfig$Type();
// @generated message type with reflection information, may provide speed optimized methods
class SectionForType$Type extends MessageType<SectionForType> {
    constructor() {
        super("elephant.replicant.SectionForType", [
            { no: 1, name: "type", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "section_uuid", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<SectionForType>): SectionForType {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.type = "";
        message.sectionUuid = "";
        if (value !== undefined)
            reflectionMergePartial<SectionForType>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: SectionForType): SectionForType {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string type */ 1:
                    message.type = reader.string();
                    break;
                case /* string section_uuid */ 2:
                    message.sectionUuid = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: SectionForType, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string type = 1; */
        if (message.type !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.type);
        /* string section_uuid = 2; */
        if (message.sectionUuid !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.sectionUuid);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message elephant.replicant.SectionForType
 */
export const SectionForType = new SectionForType$Type();
// @generated message type with reflection information, may provide speed optimized methods
class AttachmentForType$Type extends MessageType<AttachmentForType> {
    constructor() {
        super("elephant.replicant.AttachmentForType", [
            { no: 1, name: "type", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<AttachmentForType>): AttachmentForType {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.type = "";
        message.name = "";
        if (value !== undefined)
            reflectionMergePartial<AttachmentForType>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: AttachmentForType): AttachmentForType {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string type */ 1:
                    message.type = reader.string();
                    break;
                case /* string name */ 2:
                    message.name = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: AttachmentForType, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string type = 1; */
        if (message.type !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.type);
        /* string name = 2; */
        if (message.name !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.name);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message elephant.replicant.AttachmentForType
 */
export const AttachmentForType = new AttachmentForType$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ConfigureTargetResponse$Type extends MessageType<ConfigureTargetResponse> {
    constructor() {
        super("elephant.replicant.ConfigureTargetResponse", []);
    }
    create(value?: PartialMessage<ConfigureTargetResponse>): ConfigureTargetResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<ConfigureTargetResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ConfigureTargetResponse): ConfigureTargetResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ConfigureTargetResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message elephant.replicant.ConfigureTargetResponse
 */
export const ConfigureTargetResponse = new ConfigureTargetResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class RemoveTargetRequest$Type extends MessageType<RemoveTargetRequest> {
    constructor() {
        super("elephant.replicant.RemoveTargetRequest", [
            { no: 1, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<RemoveTargetRequest>): RemoveTargetRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.name = "";
        if (value !== undefined)
            reflectionMergePartial<RemoveTargetRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: RemoveTargetRequest): RemoveTargetRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string name */ 1:
                    message.name = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: RemoveTargetRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string name = 1; */
        if (message.name !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.name);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message elephant.replicant.RemoveTargetRequest
 */
export const RemoveTargetRequest = new RemoveTargetRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class RemoveTargetResponse$Type extends MessageType<RemoveTargetResponse> {
    constructor() {
        super("elephant.replicant.RemoveTargetResponse", []);
    }
    create(value?: PartialMessage<RemoveTargetResponse>): RemoveTargetResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<RemoveTargetResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: RemoveTargetResponse): RemoveTargetResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: RemoveTargetResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message elephant.replicant.RemoveTargetResponse
 */
export const RemoveTargetResponse = new RemoveTargetResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ChangeTargetStateRequest$Type extends MessageType<ChangeTargetStateRequest> {
    constructor() {
        super("elephant.replicant.ChangeTargetStateRequest", [
            { no: 1, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "action", kind: "enum", T: () => ["elephant.replicant.TargetAction", TargetAction, "TARGET_ACTION_"] }
        ]);
    }
    create(value?: PartialMessage<ChangeTargetStateRequest>): ChangeTargetStateRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.name = "";
        message.action = 0;
        if (value !== undefined)
            reflectionMergePartial<ChangeTargetStateRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ChangeTargetStateRequest): ChangeTargetStateRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string name */ 1:
                    message.name = reader.string();
                    break;
                case /* elephant.replicant.TargetAction action */ 2:
                    message.action = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ChangeTargetStateRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string name = 1; */
        if (message.name !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.name);
        /* elephant.replicant.TargetAction action = 2; */
        if (message.action !== 0)
            writer.tag(2, WireType.Varint).int32(message.action);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message elephant.replicant.ChangeTargetStateRequest
 */
export const ChangeTargetStateRequest = new ChangeTargetStateRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ChangeTargetStateResponse$Type extends MessageType<ChangeTargetStateResponse> {
    constructor() {
        super("elephant.replicant.ChangeTargetStateResponse", []);
    }
    create(value?: PartialMessage<ChangeTargetStateResponse>): ChangeTargetStateResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<ChangeTargetStateResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ChangeTargetStateResponse): ChangeTargetStateResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ChangeTargetStateResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message elephant.replicant.ChangeTargetStateResponse
 */
export const ChangeTargetStateResponse = new ChangeTargetStateResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetTargetStateRequest$Type extends MessageType<GetTargetStateRequest> {
    constructor() {
        super("elephant.replicant.GetTargetStateRequest", [
            { no: 1, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<GetTargetStateRequest>): GetTargetStateRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.name = "";
        if (value !== undefined)
            reflectionMergePartial<GetTargetStateRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetTargetStateRequest): GetTargetStateRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string name */ 1:
                    message.name = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetTargetStateRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string name = 1; */
        if (message.name !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.name);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message elephant.replicant.GetTargetStateRequest
 */
export const GetTargetStateRequest = new GetTargetStateRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetTargetStateResponse$Type extends MessageType<GetTargetStateResponse> {
    constructor() {
        super("elephant.replicant.GetTargetStateResponse", [
            { no: 1, name: "state", kind: "enum", T: () => ["elephant.replicant.TargetState", TargetState, "TARGET_STATE_"] }
        ]);
    }
    create(value?: PartialMessage<GetTargetStateResponse>): GetTargetStateResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.state = 0;
        if (value !== undefined)
            reflectionMergePartial<GetTargetStateResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetTargetStateResponse): GetTargetStateResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* elephant.replicant.TargetState state */ 1:
                    message.state = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetTargetStateResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* elephant.replicant.TargetState state = 1; */
        if (message.state !== 0)
            writer.tag(1, WireType.Varint).int32(message.state);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message elephant.replicant.GetTargetStateResponse
 */
export const GetTargetStateResponse = new GetTargetStateResponse$Type();
/**
 * @generated ServiceType for protobuf service elephant.replicant.Replication
 */
export const Replication = new ServiceType("elephant.replicant.Replication", [
    { name: "SendDocument", options: {}, I: SendDocumentRequest, O: SendDocumentResponse },
    { name: "ConfigureTarget", options: {}, I: ConfigureTargetRequest, O: ConfigureTargetResponse },
    { name: "RemoveTarget", options: {}, I: RemoveTargetRequest, O: RemoveTargetResponse },
    { name: "ChangeTargetState", options: {}, I: ChangeTargetStateRequest, O: ChangeTargetStateResponse },
    { name: "GetTargetState", options: {}, I: GetTargetStateRequest, O: GetTargetStateResponse }
]);
