/* eslint-disable */
// @generated by protobuf-ts 2.11.1 with parameter generate_dependencies,ts_nocheck,eslint_disable
// @generated from protobuf file "user/service.proto" (package "elephant.user", syntax proto3)
// tslint:disable
// @ts-nocheck
import { Messages } from "./service";
import type { DeleteInboxMessageResponse } from "./service";
import type { DeleteInboxMessageRequest } from "./service";
import type { UpdateInboxMessageResponse } from "./service";
import type { UpdateInboxMessageRequest } from "./service";
import type { ListInboxMessagesResponse } from "./service";
import type { ListInboxMessagesRequest } from "./service";
import type { PollInboxMessagesResponse } from "./service";
import type { PollInboxMessagesRequest } from "./service";
import type { PollMessagesResponse } from "./service";
import type { PollMessagesRequest } from "./service";
import type { PushInboxMessageResponse } from "./service";
import type { PushInboxMessageRequest } from "./service";
import type { PushMessageResponse } from "./service";
import type { PushMessageRequest } from "./service";
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { Settings } from "./service";
import type { PollEventLogResponse } from "./service";
import type { PollEventLogRequest } from "./service";
import type { DeletePropertiesResponse } from "./service";
import type { DeletePropertiesRequest } from "./service";
import type { SetPropertiesResponse } from "./service";
import type { SetPropertiesRequest } from "./service";
import type { GetPropertiesResponse } from "./service";
import type { GetPropertiesRequest } from "./service";
import type { DeleteDocumentResponse } from "./service";
import type { DeleteDocumentRequest } from "./service";
import type { UpdateDocumentResponse } from "./service";
import type { UpdateDocumentRequest } from "./service";
import type { ListDocumentsResponse } from "./service";
import type { ListDocumentsRequest } from "./service";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { GetDocumentResponse } from "./service";
import type { GetDocumentRequest } from "./service";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * Settings service manages configuration for authenticated users.
 *
 * All methods in this service rely on the `sub` claim from the
 * authentication (bearer) token to identify the target user.
 *
 * @generated from protobuf service elephant.user.Settings
 */
export interface ISettingsClient {
    /**
     * Gets a specific document for the authenticated user.
     *
     * @generated from protobuf rpc: GetDocument
     */
    getDocument(input: GetDocumentRequest, options?: RpcOptions): UnaryCall<GetDocumentRequest, GetDocumentResponse>;
    /**
     * Lists documents for the authenticated user.
     *
     * @generated from protobuf rpc: ListDocuments
     */
    listDocuments(input: ListDocumentsRequest, options?: RpcOptions): UnaryCall<ListDocumentsRequest, ListDocumentsResponse>;
    /**
     * Updates an existing or creates a new document for the authenticated user.
     *
     * @generated from protobuf rpc: UpdateDocument
     */
    updateDocument(input: UpdateDocumentRequest, options?: RpcOptions): UnaryCall<UpdateDocumentRequest, UpdateDocumentResponse>;
    /**
     * Deletes a document for the authenticated user.
     *
     * @generated from protobuf rpc: DeleteDocument
     */
    deleteDocument(input: DeleteDocumentRequest, options?: RpcOptions): UnaryCall<DeleteDocumentRequest, DeleteDocumentResponse>;
    /**
     * Gets properties for the authenticated user.
     *
     * @generated from protobuf rpc: GetProperties
     */
    getProperties(input: GetPropertiesRequest, options?: RpcOptions): UnaryCall<GetPropertiesRequest, GetPropertiesResponse>;
    /**
     * Sets or updates properties for the authenticated user.
     *
     * @generated from protobuf rpc: SetProperties
     */
    setProperties(input: SetPropertiesRequest, options?: RpcOptions): UnaryCall<SetPropertiesRequest, SetPropertiesResponse>;
    /**
     * Deletes properties for the authenticated user.
     *
     * @generated from protobuf rpc: DeleteProperties
     */
    deleteProperties(input: DeletePropertiesRequest, options?: RpcOptions): UnaryCall<DeletePropertiesRequest, DeletePropertiesResponse>;
    /**
     * Polls for a stream of changes (creates, updates, deletes)
     * for both documents and properties for the authenticated user.
     *
     * @generated from protobuf rpc: PollEventLog
     */
    pollEventLog(input: PollEventLogRequest, options?: RpcOptions): UnaryCall<PollEventLogRequest, PollEventLogResponse>;
}
/**
 * Settings service manages configuration for authenticated users.
 *
 * All methods in this service rely on the `sub` claim from the
 * authentication (bearer) token to identify the target user.
 *
 * @generated from protobuf service elephant.user.Settings
 */
export class SettingsClient implements ISettingsClient, ServiceInfo {
    typeName = Settings.typeName;
    methods = Settings.methods;
    options = Settings.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * Gets a specific document for the authenticated user.
     *
     * @generated from protobuf rpc: GetDocument
     */
    getDocument(input: GetDocumentRequest, options?: RpcOptions): UnaryCall<GetDocumentRequest, GetDocumentResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetDocumentRequest, GetDocumentResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * Lists documents for the authenticated user.
     *
     * @generated from protobuf rpc: ListDocuments
     */
    listDocuments(input: ListDocumentsRequest, options?: RpcOptions): UnaryCall<ListDocumentsRequest, ListDocumentsResponse> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListDocumentsRequest, ListDocumentsResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * Updates an existing or creates a new document for the authenticated user.
     *
     * @generated from protobuf rpc: UpdateDocument
     */
    updateDocument(input: UpdateDocumentRequest, options?: RpcOptions): UnaryCall<UpdateDocumentRequest, UpdateDocumentResponse> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<UpdateDocumentRequest, UpdateDocumentResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * Deletes a document for the authenticated user.
     *
     * @generated from protobuf rpc: DeleteDocument
     */
    deleteDocument(input: DeleteDocumentRequest, options?: RpcOptions): UnaryCall<DeleteDocumentRequest, DeleteDocumentResponse> {
        const method = this.methods[3], opt = this._transport.mergeOptions(options);
        return stackIntercept<DeleteDocumentRequest, DeleteDocumentResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * Gets properties for the authenticated user.
     *
     * @generated from protobuf rpc: GetProperties
     */
    getProperties(input: GetPropertiesRequest, options?: RpcOptions): UnaryCall<GetPropertiesRequest, GetPropertiesResponse> {
        const method = this.methods[4], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetPropertiesRequest, GetPropertiesResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * Sets or updates properties for the authenticated user.
     *
     * @generated from protobuf rpc: SetProperties
     */
    setProperties(input: SetPropertiesRequest, options?: RpcOptions): UnaryCall<SetPropertiesRequest, SetPropertiesResponse> {
        const method = this.methods[5], opt = this._transport.mergeOptions(options);
        return stackIntercept<SetPropertiesRequest, SetPropertiesResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * Deletes properties for the authenticated user.
     *
     * @generated from protobuf rpc: DeleteProperties
     */
    deleteProperties(input: DeletePropertiesRequest, options?: RpcOptions): UnaryCall<DeletePropertiesRequest, DeletePropertiesResponse> {
        const method = this.methods[6], opt = this._transport.mergeOptions(options);
        return stackIntercept<DeletePropertiesRequest, DeletePropertiesResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * Polls for a stream of changes (creates, updates, deletes)
     * for both documents and properties for the authenticated user.
     *
     * @generated from protobuf rpc: PollEventLog
     */
    pollEventLog(input: PollEventLogRequest, options?: RpcOptions): UnaryCall<PollEventLogRequest, PollEventLogResponse> {
        const method = this.methods[7], opt = this._transport.mergeOptions(options);
        return stackIntercept<PollEventLogRequest, PollEventLogResponse>("unary", this._transport, method, opt, input);
    }
}
/**
 * @generated from protobuf service elephant.user.Messages
 */
export interface IMessagesClient {
    /**
     * Pushes a new message to a recipient.
     *
     * @generated from protobuf rpc: PushMessage
     */
    pushMessage(input: PushMessageRequest, options?: RpcOptions): UnaryCall<PushMessageRequest, PushMessageResponse>;
    /**
     * Pushes a new inbox message to a recipient.
     *
     * @generated from protobuf rpc: PushInboxMessage
     */
    pushInboxMessage(input: PushInboxMessageRequest, options?: RpcOptions): UnaryCall<PushInboxMessageRequest, PushInboxMessageResponse>;
    /**
     * Polls for new messages for a recipient.
     *
     * @generated from protobuf rpc: PollMessages
     */
    pollMessages(input: PollMessagesRequest, options?: RpcOptions): UnaryCall<PollMessagesRequest, PollMessagesResponse>;
    /**
     * Polls for new inbox messages for a recipient.
     *
     * @generated from protobuf rpc: PollInboxMessages
     */
    pollInboxMessages(input: PollInboxMessagesRequest, options?: RpcOptions): UnaryCall<PollInboxMessagesRequest, PollInboxMessagesResponse>;
    /**
     * Lists all inbox messages for a recipient.
     *
     * @generated from protobuf rpc: ListInboxMessages
     */
    listInboxMessages(input: ListInboxMessagesRequest, options?: RpcOptions): UnaryCall<ListInboxMessagesRequest, ListInboxMessagesResponse>;
    /**
     * Updates an existing inbox message.
     *
     * @generated from protobuf rpc: UpdateInboxMessage
     */
    updateInboxMessage(input: UpdateInboxMessageRequest, options?: RpcOptions): UnaryCall<UpdateInboxMessageRequest, UpdateInboxMessageResponse>;
    /**
     * Deletes an inbox message.
     *
     * @generated from protobuf rpc: DeleteInboxMessage
     */
    deleteInboxMessage(input: DeleteInboxMessageRequest, options?: RpcOptions): UnaryCall<DeleteInboxMessageRequest, DeleteInboxMessageResponse>;
}
/**
 * @generated from protobuf service elephant.user.Messages
 */
export class MessagesClient implements IMessagesClient, ServiceInfo {
    typeName = Messages.typeName;
    methods = Messages.methods;
    options = Messages.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * Pushes a new message to a recipient.
     *
     * @generated from protobuf rpc: PushMessage
     */
    pushMessage(input: PushMessageRequest, options?: RpcOptions): UnaryCall<PushMessageRequest, PushMessageResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<PushMessageRequest, PushMessageResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * Pushes a new inbox message to a recipient.
     *
     * @generated from protobuf rpc: PushInboxMessage
     */
    pushInboxMessage(input: PushInboxMessageRequest, options?: RpcOptions): UnaryCall<PushInboxMessageRequest, PushInboxMessageResponse> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<PushInboxMessageRequest, PushInboxMessageResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * Polls for new messages for a recipient.
     *
     * @generated from protobuf rpc: PollMessages
     */
    pollMessages(input: PollMessagesRequest, options?: RpcOptions): UnaryCall<PollMessagesRequest, PollMessagesResponse> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<PollMessagesRequest, PollMessagesResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * Polls for new inbox messages for a recipient.
     *
     * @generated from protobuf rpc: PollInboxMessages
     */
    pollInboxMessages(input: PollInboxMessagesRequest, options?: RpcOptions): UnaryCall<PollInboxMessagesRequest, PollInboxMessagesResponse> {
        const method = this.methods[3], opt = this._transport.mergeOptions(options);
        return stackIntercept<PollInboxMessagesRequest, PollInboxMessagesResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * Lists all inbox messages for a recipient.
     *
     * @generated from protobuf rpc: ListInboxMessages
     */
    listInboxMessages(input: ListInboxMessagesRequest, options?: RpcOptions): UnaryCall<ListInboxMessagesRequest, ListInboxMessagesResponse> {
        const method = this.methods[4], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListInboxMessagesRequest, ListInboxMessagesResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * Updates an existing inbox message.
     *
     * @generated from protobuf rpc: UpdateInboxMessage
     */
    updateInboxMessage(input: UpdateInboxMessageRequest, options?: RpcOptions): UnaryCall<UpdateInboxMessageRequest, UpdateInboxMessageResponse> {
        const method = this.methods[5], opt = this._transport.mergeOptions(options);
        return stackIntercept<UpdateInboxMessageRequest, UpdateInboxMessageResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * Deletes an inbox message.
     *
     * @generated from protobuf rpc: DeleteInboxMessage
     */
    deleteInboxMessage(input: DeleteInboxMessageRequest, options?: RpcOptions): UnaryCall<DeleteInboxMessageRequest, DeleteInboxMessageResponse> {
        const method = this.methods[6], opt = this._transport.mergeOptions(options);
        return stackIntercept<DeleteInboxMessageRequest, DeleteInboxMessageResponse>("unary", this._transport, method, opt, input);
    }
}
